config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :items
  resources :messages
  resources :searches

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :widgets
  resources :users
 

  root 'pages#index'
  get 'info' => 'pages#info'
  get 'inbox' => 'messages#index'
  get 'tags/:tag', to: 'items#index', as: "tag"
  get 'categories/:category', to: 'items#index', as: "category"
  get 'users/:id/promote', to: 'users#promote', as: 'promote_user'
  get 'users/:id/demote', to: 'users#demote', as: 'demote_user'
  match '/charges/', to: 'charges#create', via: 'post'
  match '/claims/', to: 'claims#create', via: 'post' 
 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user) 
       user ||= User.new # guest user (not logged in)

       alias_action :read, :create, :update, :destroy, :to => :crud
  
    #     can :read, :all
         can :crud, Item, :user_id => user.id
       
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :user
  validates :user_id, presence: true
  validates :name, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }, presence: true
 
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.downcase.strip).first_or_create!
    end
  end
 
  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).items
  end

  
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :profile, :presence => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/search.rb
class Search < ActiveRecord::Base

def items
	@items ||= find_items
end

private

def find_items
    items =Item.order(:name)
    items =items.where("name ilike ?", "%#{name}%") if name.present?
    items =items.where("category ilike ?", "%#{category}%") if category.present?
    #items =items.where("tag ilike ?", "%#{tag}%") if tag.present?
    items =items.where("condition ilike ?", "%#{condition}%") if condition.present?
    items =items.where("price >= ?", minimum_price) if minimum_price.present?
    items =items.where("price <= ?", maximum_price) if maximum_price.present?
    items
end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :items, through: :taggings
  
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  has_many :items, dependent: :destroy
  has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id", dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]
  after_create :send_welcome_msg

  validates_confirmation_of :password
  after_create :add_profile

  def add_profile
 	self.create_profile
  end

  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end

  #user rating
  ratyrate_rateable "rating"
  ratyrate_rater

  def user_params
    params.require(:user).permit(:username, :name, :avatar_url, :email, :password, :password_confirmation)
  end

  # change this later
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
	data = access_token.info
    user = User.where(:email => data["email"]).first

	unless user
      user = User.create(name: access_token.extra.raw_info.name,
        provider: data["provider"],
        uid: data["uid"],
        email: data["email"],
        password: Devise.friendly_token[0,20],
      )
    end

	user
  end

  def send_welcome_msg
    message = Message.new
    message.user_id = self.id
    message.recipient_id = self.id
    message.subject = "Hello, #{self.full_name}!"
    message.body = "Hello, #{self.full_name}! Welcome to the Triton Trade community! Here is a quick guide to get you start buying and selling items to other members in our community.\n\nNavigation bar: Access quick features such as clicking our logo to be redirected to the home page, explore categories of items, or go to account management.\n\nHomepage: Search items by name or click one of the featured buttons below the search bar to be redirected to that page.\n\nBuy: View the listing of items for sale from other users. \n\nSell: Post an item you wish to be sold.\n\nFree: View items that are listed as free.\n\nThanks again for joining our community. Happy Trading!\nTriton Trade\n"
    message.save
  end

  # Bind/Create User
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
      user = User.create(provider: data["provider"],
        uid: data["uid"],
        email: data["email"],
        password: Devise.friendly_token[0,20]
      )
    end

    user
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users= User.all
  end

  def show
    @user = User.find(params[:id])
    @items = Item.where(user_id: params[:id])
    @purchaseditems = Item.where(buyeremail: User.find(params[:id]).email )
  end

  def create
    User.create(user_params)
  end

  def update
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to :back
  end

  def promote
    User.find(params[:id]).update_attribute :admin, true
    redirect_to :back
  end

  def demote
    User.find(params[:id]).update_attribute :admin, false
    redirect_to :back
  end

  private
  def user_params
    params.require(:user).permit(:name, :provider, :uid, :email);
  end

end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    def tag_links(tags)
      tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sell_helper.rb
module SellHelper
end

app/views/users/index.html.erb
<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user_path(user) %></td>
        <% if current_user.try(:admin?) %>
          <% if user.admin %>
            <td><%= link_to 'Demote', demote_user_path(user) %><td>
          <% else %>
            <td><%= link_to 'Promote', promote_user_path(user) %><td>
          <% end %>
          <td><%= link_to 'Ban', user, method: :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<head>
<style>
  body {background-color: rgba(52,152,219,.75)};
  body a:hover { text-decoration:none; }
  .border-form-div2 { background: white;  margin-left: auto; margin-right: auto; }
  .border-form-div2 h1 { font-family: "Oswald", cursive; padding-bottom: 15px; }
  .border-form-div2 .editprof { font-family: Arial, Helvetica, sans-serif; font-size: 15px; }
  .border-form-div2 img { padding-left: 2%; float: left; padding-right: 10px; }
  .border-form-div2 ul { list-style: none; }
  .itemshowcase { clear: both; }
  .itemshowcase .it { padding-left: 2%; padding-top:40px; }
  .products { padding-left:2%; }
  .products li { display: inline-block; width: 140px; vertical-align:top; }
  .products a:hover { color: #3498db; background-color: transparent; }
  .products h1, h4 { font-family: "Oswald", sans-serif; text-align: center; }
  .products p { text-align: center; }
  .products p:hover { text-decoration: none; }

  .purchaseditemshowcase { clear: both; }
  .purchaseditemshowcase .it { padding-left: 2%; padding-top:40px; }
  .purchasedproducts { padding-left:2%; }
  .purchasedproducts li { display: inline-block; width: 140px; vertical-align:top; }
  .purchasedproducts a:hover { color: #3498db; background-color: transparent; }
  .purchasedproducts h1, h4 { font-family: "Oswald", sans-serif; text-align: center; }
  .purchasedproducts p { text-align: center; }
  .purchasedproducts p:hover { text-decoration: none; }
</style>
</head>

<body>
	<div class="border-form-div2">
    <%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track" => false %>
	<center><h1><%= @user.name %>

	<% if user_signed_in? && current_user.id == @user.id%>
		<%# if can? :crud, @user %>
			<center><p class="editprof" ><%= link_to 'Edit Profile', edit_user_registration_path %></p>
		<%# end %>
	<% end %></h1></center>

	<p><%= image_tag @user.avatar_url.blank? ? ("http://community.blrstartups.com/content/plugins/techchamp/assets/avatars/anon.png") : @user.avatar_url, :width => 200, :height => 200, :crop => :fill %><p>

	<ul>
	    <li><strong>Email:</strong> <%= @user.email %></li>
	    <li><strong>Date of Birth:</strong> <%= @user.date_of_birth.nil? ? "" : @user.date_of_birth.to_time.strftime('%b %d, %Y') %></li>
	    <li><strong>PID:</strong> <%= @user.PID.nil? ? "" : @user.PID %><br><br></li>
	    <% if user_signed_in? %>
	    <li><strong>Rating:</strong> <%= rating_for @user, "rating", disable_after_rate: true, star_path:'/images/', cancel_place: 'left', cancel_hint: 'Cancel this vote!', space: true %></li>
	    <% end %>
	</ul>

<div class = "itemshowcase">
	<p class="it"><center><strong>Items for Sale</strong></center></p>
	<!--display user's items for sale -->
	<ul class="products">
		<% @items.each do |item| %>
			<% if item.is_sold != true %>
			<li>
				<p><%= image_tag item.image_url.blank? ? ("https://www.saveful.com/img/no_image_available.jpg") : item.image_url, :width => 140, :height => 140, :crop => :fill %></p>
				<h4><%= link_to item.name, item %></h4>
				<p><%= number_to_currency(item.price) %></p>
			</li>
			<% end %>
		<% end %>
	</ul>
</div>

      <% if user_signed_in? && current_user.id == @user.id%>
           <%# if can? :crud, @user %>

<div class = "purchaseditemshowcase">
	<p class="purchasedit"><center><strong>Items Purchased</strong></center></p>
	<!--display user's purchased items -->
	<ul class="purchasedproducts">
		<% @purchaseditems.each do |pitem| %>
			<li>
				<p><%= image_tag pitem.image_url.blank? ? ("https://www.saveful.com/img/no_image_available.jpg") : pitem.image_url, :width => 140, :height => 140, :crop => :fill %></p>
				<h4><%= link_to pitem.name, pitem %></h4>
				<p><%= number_to_currency(pitem.price) %></p>
			</li>
		<% end %>
	</ul>
</div>


		<!--<center><p>< % = link_to 'Edit Profile', edit_user_registration_path %></p></center>-->
           <%# end %>
        <% end %>


	</div>
</body>