config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :items
  resources :messages
  resources :searches

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :widgets
  resources :users
 

  root 'pages#index'
  get 'info' => 'pages#info'
  get 'inbox' => 'messages#index'
  get 'tags/:tag', to: 'items#index', as: "tag"
  get 'categories/:category', to: 'items#index', as: "category"
  get 'users/:id/promote', to: 'users#promote', as: 'promote_user'
  get 'users/:id/demote', to: 'users#demote', as: 'demote_user'
  match '/charges/', to: 'charges#create', via: 'post'
  match '/claims/', to: 'claims#create', via: 'post' 
 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user) 
       user ||= User.new # guest user (not logged in)

       alias_action :read, :create, :update, :destroy, :to => :crud
  
    #     can :read, :all
         can :crud, Item, :user_id => user.id
       
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :user
  validates :user_id, presence: true
  validates :name, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }, presence: true
 
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.downcase.strip).first_or_create!
    end
  end
 
  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).items
  end

  
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :profile, :presence => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/search.rb
class Search < ActiveRecord::Base

def items
	@items ||= find_items
end

private

def find_items
    items =Item.order(:name)
    items =items.where("name ilike ?", "%#{name}%") if name.present?
    items =items.where("category ilike ?", "%#{category}%") if category.present?
    #items =items.where("tag ilike ?", "%#{tag}%") if tag.present?
    items =items.where("condition ilike ?", "%#{condition}%") if condition.present?
    items =items.where("price >= ?", minimum_price) if minimum_price.present?
    items =items.where("price <= ?", maximum_price) if maximum_price.present?
    items
end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :items, through: :taggings
  
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  has_many :items, dependent: :destroy
  has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id", dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]
  after_create :send_welcome_msg

  validates_confirmation_of :password
  after_create :add_profile

  def add_profile
 	self.create_profile
  end

  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end

  #user rating
  ratyrate_rateable "rating"
  ratyrate_rater

  def user_params
    params.require(:user).permit(:username, :name, :avatar_url, :email, :password, :password_confirmation)
  end

  # change this later
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
	data = access_token.info
    user = User.where(:email => data["email"]).first

	unless user
      user = User.create(name: access_token.extra.raw_info.name,
        provider: data["provider"],
        uid: data["uid"],
        email: data["email"],
        password: Devise.friendly_token[0,20],
      )
    end

	user
  end

  def send_welcome_msg
    message = Message.new
    message.user_id = self.id
    message.recipient_id = self.id
    message.subject = "Hello, #{self.full_name}!"
    message.body = "Hello, #{self.full_name}! Welcome to the Triton Trade community! Here is a quick guide to get you start buying and selling items to other members in our community.\n\nNavigation bar: Access quick features such as clicking our logo to be redirected to the home page, explore categories of items, or go to account management.\n\nHomepage: Search items by name or click one of the featured buttons below the search bar to be redirected to that page.\n\nBuy: View the listing of items for sale from other users. \n\nSell: Post an item you wish to be sold.\n\nFree: View items that are listed as free.\n\nThanks again for joining our community. Happy Trading!\nTriton Trade\n"
    message.save
  end

  # Bind/Create User
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
      user = User.create(provider: data["provider"],
        uid: data["uid"],
        email: data["email"],
        password: Devise.friendly_token[0,20]
      )
    end

    user
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :set_item,  only: [:show, :edit, :update, :destroy]

before_action :authenticate_user!, only: [:edit, :update, :destroy]

before_filter :authenticate_user!, only: [:new]

  respond_to :html

  def index
    if params[:tag] == "free"
       @items = Item.where("price <= ?", 0) | Item.tagged_with(params[:tag]) 
    elsif params[:tag]
       @items = Item.tagged_with(params[:tag])
    elsif params[:category]
       @items = Item.where(category: params[:category])
    else
       @items = Item.all
    end
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    respond_with(@item)
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :is_sold, :price, :condition, :image_url, :user_id, :category, :all_tags, :buyeremail);
    end
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    def tag_links(tags)
      tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sell_helper.rb
module SellHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true %><br>
    
    <%= f.label :condition %><br>
    <%= f.select :condition, [['Fair', 'Fair'], ['Used', 'Used'], ['Good', 'Good'], ['New', 'New']], autofocus: true %><br>

    <!--<select>
	<option value="select" selected>Select One</option>
	<option value="clothes">Clothes</option>
	<option value="textbooks">Textbooks</option>
	<option value="furniture">Furniture</option>
	<option value="miscellaneous">Miscellaneous</option>
   </select><br>-->
    
    <%= f.label :description %><br>
    <%= f.text_area :description %><br>

    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, autofocus: true %><br>

    <%= f.label :price %><br>
    <%= f.number_field :price, :class => 'text_field', :step => 'any', autofocus: true %><br>

    <%= f.label :category %><br>
    <%= f.select :category, [['Miscellaneous', 'Miscellaneous'], ['Clothes', 'Clothes'], ['Textbooks', 'Textbooks'], ['Furniture', 'Furniture']], autofocus: true %><br>

    <%= f.label :all_tags %><br>
    <%= f.text_field :all_tags, placeholder: "Tags separated with ," %><br>
    
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<li id="item-<%= item.id %>">
  <%= link_to gravatar_for(item.user, size: 50), item.user %>
  <span class="user"><%= link_to item.user.name, item.user %></span>
  <span class="item"><%= item.name %></span>
  <span class="condition"><%= item.condition %></span>
  <span class="price"><%= item.price %></span>
  <span class="tags"><%=raw tag_links(item.all_tags) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(item.created_at) %> ago.
  </span>
</li>

app/views/items/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/items/edit.html.erb
<head>
	<style>
		body { background-color: rgba(52,152,219,.75)};
		body h1 {  font-family: "Oswald", sans-serif; }
	</style>
</head>

<body>
<div class="border-form-div">
	<center><h1>Editing Item</h1></center>

	<%= render 'form' %>

	<center><%= link_to 'Go Back', @item %></center>
</div>
</body>

app/views/items/index.html.erb
<head>
	<style>
		body h1 { font-family: "Oswald", sans-serif; text-align: center; }
		/* body { background-color: rgba(52,152,219,.75); } */
		.products li { display: inline-block; width: 400px; vertical-align:top; }
		body .new { padding: 5px; }
		.products { padding-top: 50px; }
		/*---------------------------------------*/
		a { color: #787878; text-decoration: none; font-size: 14px; }
		a:hover { color: #3498db; background: transparent; text-decoration: none; }
		.products .image { bottom: 0; display: block; height: auto; max-width: 100%; }
		.clearfix p { margin: 0; }
		.clearfix h4 { font-family: "Oswald", sans-serif; color: #fff; margin: 0; padding: 0; }
		.clearfix .pricebutton { background: #0084b4; border-radius: 3px; color: #fff; display: block; font-weight: bold; margin: 0; padding: 10px }
		.clearfix .pricebutton:hover { background: #2D76B9; color: #fff; }
		.products li { border: 6px solid #fff; box-shadow: 0 0 5px rgba(0, 0, 0, .3); overflow: hidden; width: 330px; padding-bottom: 3px; position: relative; }
		.products li:hover .clearfix { opacity: 1; -webkit-transform: translateY(0); -moz-transform: translateY(0); -ms-transform: translateY(0);	-o-transform: translateY(0); transform: translateY(0); -webkit-transition: -webkit-transform .4s, opacity .1s;	-moz-transition: -moz-transform .4s, opacity .1s; -ms-transition: -ms-transform .4s, opacity .1s; -o-transition: -o-transform .4s, opacity .1s;	transition: transform .4s, opacity .1s; }

		.products li .clearfix { background: rgba(255,255,255,0.6); bottom: 0; color: #fff; height: 80px; left: 0; opacity: 0; padding: 10px; position: absolute; -webkit-transform: translateY(100%); -moz-transform: translateY(100%); -ms-transform: translateY(100%); -o-transform: translateY(100%); transform: translateY(100%); -webkit-transition: -webkit-transform .4s, opacity .1s .3s; -moz-transition: -moz-transform .4s, opacity .1s .3s; -ms-transition: -ms-transform .4s, opacity .1s .3s; -o-transition: -o-transform .4s, opacity .1s .3s; transition: transform .4s, opacity .1s .3s; width: 320px; }	
</style>
</head>

<body>
<% if request.original_url == "http://triton-trade.herokuapp.com/tags/free" %>
<h1>For Free</h1>
<% else %>
<h1>For Sale</h1>
<% end %>

<% if user_signed_in? %>
  <center><%= link_to new_item_path, :method => :get do %>
		<button class="new">New Item</button><br>
	  <% end %>
   </center>
<% end %>

<center><ul class="products">
<% @items.each do |item| %>
	<% unless item.is_sold %>
	<li>
		<div class="image"><%= image_tag item.image_url.blank? ? ("https://www.saveful.com/img/no_image_available.jpg") : item.image_url, :width => 300, :height => 300, :crop => :fill %></div>
		<div class="clearfix">
			<h4><%= link_to item.name, item %></h4>
			<!--<p>< % = # link_to '$'item.price, item.buy % ></p>-->
			<p><%= raw tag_links(item.all_tags) %></p>
			<p class="pricebutton"><%= number_to_currency(item.price) %></p>
		</div>
	</li>
	<% end %>
<% end %>
</ul></center>
   
</body>

app/views/items/new.html.erb
<head>
	<style>
		body { background-color: rgba(52,152,219,.75)}
		body h1 { font-family: "Oswald", sans-serif; }
	</style>
</head>

<body>
<div class="border-form-div">
	<center><h1>New item</h1></center>

	<%= render 'form' %>

	<p><center><%= link_to 'Back', items_path %></center><p/>
</div>
</body>

	

app/views/items/show.html.erb
<head>
	<style>
		body h1 { font-family: "Oswald", sans-serif; text-transform: uppercase; margin-bottom: 20px; }
		.pic { padding-left: 10%; float: left; padding-right: 10px; }
		.iteminfo li { list-style: none; display: block; margin-bottom: 10px; text-align: left; }
		.iteminfo a:hover { text-decoration: none; }
		.border-form-div2 .buy { padding: 5px; }
		/*.iteminfo .price { font-size: 15px; } */
		body { background-color: rgba(52, 152, 219, .75) }
		.border-form-div2 { /*border-radius: 25px; border: 2px solid #3498db; background: #FFFFFF;*/
			   max-width: 700px; max-height: 570px; position: absolute;
			   top:0; bottom:0; left:0; right:0; margin: auto;}
		.bottom { clear: both; }
	</style>
</head>

<body>
<p id="notice"><%= notice %></p>
<!-- This div is the box containing the item elements -->
<div class="border-form-div2">

<center><h1><%= @item.name %></h1>

<p><div class="pic">
  <%= image_tag @item.image_url.blank? ? ("https://www.saveful.com/img/no_image_available.jpg") : @item.image_url, :width => 400, :height => 400, :crop => :fill %>
</div></p>

<ul class="iteminfo">
	<li><strong>Item Condition:</strong><br>
	<%= @item.condition %><br></li>

	<li><strong>Description:</strong><br>
	<%= @item.description %><br></li>

	<li class="price"><strong>Price:</strong><br><%= number_to_currency(@item.price) %><br></li>

	<li><strong>Seller:</strong><br>
	<%= link_to @item.user.name.blank? ? @item.user.email : @item.user.name, user_path(@item.user) %><br></li>

	<% unless @item.category.nil? %>
		<li><strong>Category:</strong><br>
		<%= link_to @item.category, category_path(@item.category) %><br></li>
	<% end %>

	<li><strong>Tags:</strong><br>
	<%= raw tag_links(@item.all_tags) %><br></li>
</ul>

<div class="bottom">

<% if @item.is_sold %>
<li class="SOLD"><strong>This item has been SOLD</strong></li>

<% else %>
	<% if user_signed_in? %>
		<% if current_user.email != @item.user.email %>
	<% if @item.all_tags.include?("free") || @item.price <= 0 %>
		<%= form_tag({controller: "claims", action: "create"}, mthod: "post") do %>
		<%= submit_tag("Claim Item") %>
  <%= hidden_field_tag :item_price, @item.price %>
  <%= hidden_field_tag :item_id, @item.id %>
  <%= hidden_field_tag :current_useremail, current_user.email %>
  <%= hidden_field_tag :current_userid, current_user.id %>
		<% end %>
	<% else %>
		<%= form_tag({controller: "charges", action: "create"}, mthod: "post") do %> 
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Item price"
          data-amount= "<%=@item.price * 100 %>"></script>
 
  <%= hidden_field_tag :item_price, @item.price %>
  <%= hidden_field_tag :item_id, @item.id %>
  <%= hidden_field_tag :current_useremail, current_user.email %>
  <%= hidden_field_tag :current_userid, current_user.id %>
			<% end %>
		   <% end %>
		<% end %>
	<% end %>
<% end %>

<% if user_signed_in? %>
<br>
  <% if can? :crud, @item %>
    <%= link_to 'Edit', edit_item_path(@item) %> | <%= link_to 'Delete', @item, method: :delete %> | 
  <% elsif current_user.admin %>
    <%= link_to 'Delete', @item, method: :delete %> | 
  <% end %>
<% end %>

<%= link_to 'Go Back', items_path %></center>

</div>
</div>


</body>