config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :items
  resources :messages
  resources :searches

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :widgets
  resources :users
 

  root 'pages#index'
  get 'info' => 'pages#info'
  get 'inbox' => 'messages#index'
  get 'tags/:tag', to: 'items#index', as: "tag"
  get 'categories/:category', to: 'items#index', as: "category"
  get 'users/:id/promote', to: 'users#promote', as: 'promote_user'
  get 'users/:id/demote', to: 'users#demote', as: 'demote_user'
  match '/charges/', to: 'charges#create', via: 'post'
  match '/claims/', to: 'claims#create', via: 'post' 
 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user) 
       user ||= User.new # guest user (not logged in)

       alias_action :read, :create, :update, :destroy, :to => :crud
  
    #     can :read, :all
         can :crud, Item, :user_id => user.id
       
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :user
  validates :user_id, presence: true
  validates :name, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }, presence: true
 
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.downcase.strip).first_or_create!
    end
  end
 
  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).items
  end

  
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :profile, :presence => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/search.rb
class Search < ActiveRecord::Base

def items
	@items ||= find_items
end

private

def find_items
    items =Item.order(:name)
    items =items.where("name ilike ?", "%#{name}%") if name.present?
    items =items.where("category ilike ?", "%#{category}%") if category.present?
    #items =items.where("tag ilike ?", "%#{tag}%") if tag.present?
    items =items.where("condition ilike ?", "%#{condition}%") if condition.present?
    items =items.where("price >= ?", minimum_price) if minimum_price.present?
    items =items.where("price <= ?", maximum_price) if maximum_price.present?
    items
end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :items, through: :taggings
  
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  has_many :items, dependent: :destroy
  has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id", dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]
  after_create :send_welcome_msg

  validates_confirmation_of :password
  after_create :add_profile

  def add_profile
 	self.create_profile
  end

  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end

  #user rating
  ratyrate_rateable "rating"
  ratyrate_rater

  def user_params
    params.require(:user).permit(:username, :name, :avatar_url, :email, :password, :password_confirmation)
  end

  # change this later
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
	data = access_token.info
    user = User.where(:email => data["email"]).first

	unless user
      user = User.create(name: access_token.extra.raw_info.name,
        provider: data["provider"],
        uid: data["uid"],
        email: data["email"],
        password: Devise.friendly_token[0,20],
      )
    end

	user
  end

  def send_welcome_msg
    message = Message.new
    message.user_id = self.id
    message.recipient_id = self.id
    message.subject = "Hello, #{self.full_name}!"
    message.body = "Hello, #{self.full_name}! Welcome to the Triton Trade community! Here is a quick guide to get you start buying and selling items to other members in our community.\n\nNavigation bar: Access quick features such as clicking our logo to be redirected to the home page, explore categories of items, or go to account management.\n\nHomepage: Search items by name or click one of the featured buttons below the search bar to be redirected to that page.\n\nBuy: View the listing of items for sale from other users. \n\nSell: Post an item you wish to be sold.\n\nFree: View items that are listed as free.\n\nThanks again for joining our community. Happy Trading!\nTriton Trade\n"
    message.save
  end

  # Bind/Create User
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
      user = User.create(provider: data["provider"],
        uid: data["uid"],
        email: data["email"],
        password: Devise.friendly_token[0,20]
      )
    end

    user
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    def tag_links(tags)
      tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sell_helper.rb
module SellHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="row">
		<div class="col-sm-12">
			<p>
				<a href="../info">About Us</a> | &copy; Team OBT. All rights reserved.
			</p>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-default navbar-fixed-top" role="banner">
	<nav role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">
					<text>Triton Trade</text>
				</a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Browse<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><%= link_to "Clothes", category_path("Clothes") %></li>
							<li><%= link_to "Textbook", category_path("Textbooks") %></li>
							<li><%= link_to "Furniture", category_path("Furniture") %></li>
							<li><%= link_to "Miscellaneous", category_path("Miscellaneous") %></li>
							<li class="divider"></li>
							<li><a href="../items">Explore</a></li>
						</ul>
					</li>
				</ul>

				<ul>
				<!-- Search field -->
				<% unless params[:controller] == 'pages' and params[:action] == 'index' %>

					<div class="col-sm-4">
					<%= form_for @search do |f| %>
						<div class="input-group">
							<%= f.text_field :name, class: "form-control input-sm", placeholder: "Find something you want!" %>
							<span class="input-group-btn">
							<%= button_tag(type: "submit", class: "btn btn-default btn-sm") do %>
							<span class="glyphicon glyphicon-search"></span>
							<% end %>
							</span>
						</div>
					<% end %>
					</div>
				<% end %>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<!--<li><%= link_to image_tag("http://static.viewbook.com/images/social_icons/facebook_16.png"), user_omniauth_authorize_path(:facebook) %></li>
						<li><%= link_to image_tag("http://static.viewbook.com/images/social_icons/google_16.png"), user_omniauth_authorize_path(:google_oauth2) %></li>-->
					<% if user_signed_in? %>

					<li class="rightbutton"><%= link_to users_path do %>
						<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>   Members
						<% end %>
					</li>
					<li class="rightbutton"><%= link_to inbox_path do %>
						<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>   Inbox
						<% end %>
					</li>


					<li><a class="navbartext">Hello, <%= current_user.name.blank? ? current_user.email : current_user.name  %>!</a></li>
					<li class="rightbuttons"><%= link_to current_user do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>   Profile
						<% end %>
					</li>

					<li class="rightbuttons"><%= link_to destroy_user_session_path, :method => :delete do %>
						<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>   Sign Out											<%end%>
					</li>

					<!--<li><%= link_to "Edit Profile",edit_user_registration_path %></li>-->

					<% else %>

					<li class="rightbuttons"><%= link_to new_user_session_path do %>
						<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>   Login
					    	<% end %>
					</li>

					<li class="rightbuttons"><%= link_to new_user_registration_path do %>
						<span class="glyphicon glyphicon-grain" aria-hidden="true"></span>   Sign Up
					    <% end %>
					</li>


					<!--<li class="rightbuttons"><%= link_to new_user_session_path do %>
						<button type="button" class="btn btn-default btn-sm">Log in</button>
						<%end%>
					</li>

					<li class="rightbuttons"><%= link_to new_user_registration_path do %>
						<button type="button" class="btn btn-default btn-sm">Sign Up For Free</button>
						<%end%>
					</li>-->

					<% end %>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container-fluid -->
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Triton Trade</title>
    <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>     
    <link href='//fonts.googleapis.com/css?family=Poiret+One|Lobster|Droid+Serif|Playfair+Display+SC:400italic|Oswald|Berkshire+Swash|Satisfy|Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' unless params[:controller] == 'items' and params[:action] == 'show' %>
  </body>
</html>

app/views/pages/index.erb
<div class = "main">
	<img src = "http://i.imgur.com/ET2tXbK.png">
</div>
<div class = "logo">
	<h1>Triton Trade</h1>
</div>


<div class="row search">
	<div class="col-sm-6 col-sm-offset-3">
		<%= form_for @search do |f| %>
			<div class="input-group">
				<%= f.text_field :name, class: "form-control input-sm", placeholder: "Find something you want!" %>
				<span class="input-group-btn">
				<%= button_tag(type: "submit", class: "btn btn-default btn-sm") do %>
				<span class="glyphicon glyphicon-search"></span>
				<% end %>
				</span>
			</div>
		<% end %>
	</div>
</div>

<ul class="quicklinks">
	<li><a href="./items">BUY</a></li>
	<li><a href="./items/new">SELL</a></li>
	<li><a href="./tags/free">FREE</a></li>
	<!-- <li><a href="./searches/new">Adv Search</a></li> -->
</ul>

app/views/pages/info.erb
    <!-- Page Content -->
    <div class="container">

        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <center><h1 class="page-header">About Triton Trade
                </h1></center>
                <p> Triton Trade is a web application that is desgined as an online marketplace for UCSD students. Once their accounts have been registered, users can sign in to buy, sell, and trade 
		a wide variety of items with other users. With this application, users will have an organized and secure platform to perform these transactions. This application also contains convenient
		features such as searching for items and browsing by category in order to improve the user's experience. Happy trading, Tritons!</p>
            </div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Team OBT</h2>
		<p>Team Orange Beta Testers is a group of undergraduate developers producing software for our CSE110: Software Engineering course at the University of California, San Diego. 
		This web application is our first product to be released in a professional environment. We hope you will enjoy our product as much as we did to develop it!
		</p>
            </div>

            <div class="col-lg-12 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://i.imgur.com/XobZupf.jpg" alt="" style="height: 300px; width: 300px;">
                <h3>Nicholas Lopez
                    <p>
                    Project Manager
                    </p>
                </h3>
            </div>                
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="https://s-media-cache-ak0.pinimg.com/originals/c2/b7/ef/c2b7ef9e1ea583462dcbac87817e9baf.jpg" alt="" style="height: 300px; width: 300px;">
                <h3>James Lee
                    <p>
                    UI Designer
                    </p>
                </h3>
            </div>
             <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="https://c402277.ssl.cf1.rackcdn.com/photos/6526/images/hero_small/sloth_(c)_Jorge_Salas_International_Expeditions.JPG?1394634201" alt="" style="height: 300px; width: 300px;">
                <h3>Dominic Gomez
                    <p>
                    Technical Lead
                    </p>
                </h3>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://www.abc.net.au/news/image/1649534-3x2-940x627.jpg" alt="" style="height: 300px; width: 300px;">
                <h3>Jeffrey Wang
                    <p>
                    Quality Assurance
                    </p>
                </h3>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://ak-hdl.buzzfed.com/static/enhanced/terminal05/2012/4/12/16/enhanced-buzz-30409-1334261955-240.jpg" alt="" style="height: 300px; width: 300px;">
                <h3>Jessie Zhu
                    <p>
                    UI Designer
                    </p>
                </h3>
            </div>            
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://www.darkgovernment.com/news/wp-content/uploads/2014/01/laughing-donkey.jpg" alt="" style="height: 300px; width: 300px;">
                <h3>Kevin Chang
                    <p>
                    UI Designer
                    </p>
                </h3>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://i.imgur.com/P9EoA2q.jpg" alt="" style="height: 300px; width: 300px;">
                <h3>Mark Huang
                    <p>
                    Architect
                    </p>
                </h3>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://i.imgur.com/4sEWb0Z.jpg" alt="" style="height: 300px; width: 300px;">
                <h3>Michael Park
                    <p>
                    Architect
                    </p>
                </h3>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://thewondrous.com/wp-content/uploads/2012/12/The-Cutest-Corgi-Ever-03.jpg" alt="" style="height: 300px; width: 300px;">
                <h3>Roy Tsai
		    <p>
                    Business Analyst
		    </p>
                </h3>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://www.awf.org/sites/default/files/media/gallery/wildlife/Mountain%20Gorilla/Csholley_baby_g.jpg?itok=QrzbcN5M" alt="" style="height: 300px; width: 300px;">
                <h3>Steven Jin
                    <p>
                    Architect
                    </p>
                </h3>
            </div>
        </div>

        <hr>
    </div>
    <!-- /.container -->

 

app/views/pages/login_index.erb
<!DOCTYPE html>
<html>
<head>
<title>Facebook Login JavaScript Example</title>
<meta charset="UTF-8">
</head>
<body>
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1451454388480735',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.2
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>

</body>
</html>

app/views/pages/login_index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Facebook Login JavaScript Example</title>
<meta charset="UTF-8">
</head>
<body>
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1451454388480735',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.2
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>

</body>
</html>

app/views/shared/_nav_bar.html.erb
<header class="navbar-default navbar-fixed-top" role="banner">
	<nav role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">
					<text>Triton Trade</text>
				</a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Browse<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><%= link_to "Clothes", category_path("Clothes") %></li>
							<li><%= link_to "Textbook", category_path("Textbooks") %></li>
							<li><%= link_to "Furniture", category_path("Furniture") %></li>
							<li><%= link_to "Miscellaneous", category_path("Miscellaneous") %></li>
							<li class="divider"></li>
							<li><a href="../items">Explore</a></li>
						</ul>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<!--<li><%= link_to image_tag("http://static.viewbook.com/images/social_icons/facebook_16.png"), user_omniauth_authorize_path(:facebook) %></li>
						<li><%= link_to image_tag("http://static.viewbook.com/images/social_icons/google_16.png"), user_omniauth_authorize_path(:google_oauth2) %></li>-->
					<% if user_signed_in? %>

					<li class="rightbutton"><%= link_to users_path do %>
						<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>   Members
						<% end %>
					</li>
					<li class="rightbutton"><%= link_to inbox_path do %>
						<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>   Inbox
						<% end %>
					</li>


					<li><a class="navbartext">Hello, <%= current_user.name.blank? ? current_user.email : current_user.name  %>!</a></li>
					<li class="rightbuttons"><%= link_to current_user do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>   Profile
						<% end %>
					</li>

					<li class="rightbuttons"><%= link_to destroy_user_session_path, :method => :delete do %>
						<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>   Sign Out											<%end%>
					</li>

					<!--<li><%= link_to "Edit Profile",edit_user_registration_path %></li>-->

					<% else %>

					<li class="rightbuttons"><%= link_to new_user_session_path do %>
						<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>   Login
					    	<% end %>
					</li>

					<li class="rightbuttons"><%= link_to new_user_registration_path do %>
						<span class="glyphicon glyphicon-grain" aria-hidden="true"></span>   Sign Up
					    <% end %>
					</li>


					<!--<li class="rightbuttons"><%= link_to new_user_session_path do %>
						<button type="button" class="btn btn-default btn-sm">Log in</button>
						<%end%>
					</li>

					<li class="rightbuttons"><%= link_to new_user_registration_path do %>
						<button type="button" class="btn btn-default btn-sm">Sign Up For Free</button>
						<%end%>
					</li>-->

					<% end %>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container-fluid -->
	</nav>
</header>